Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,6 +6,7 @@ jobs:
   build:
     name: Build my project ✨
     runs-on: ubuntu-latest
+
     steps:
       # Checkout
       - name: Checkout repository
@@ -20,6 +21,14 @@ jobs:
           key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
           restore-keys: |
             Library-
+
+      # Ensure clean state
+      - name: Check for uncommitted changes
+        run: git diff --exit-code || (echo "Uncommitted changes found, aborting workflow." && exit 1)
+
+      # List modified files
+      - name: List modified files
+        run: git status
 
       # Test
       - name: Run tests
@@ -40,9 +49,18 @@ jobs:
           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
         with:
           targetPlatform: WebGL
+          allowDirtyBuild: true  # Use this if you choose to ignore the dirty branch (not recommended)
 
       # Output
       - uses: actions/upload-artifact@v3
         with:
           name: Build
           path: build
+
+      # Upload modified files as artifacts
+      - name: Upload modified files as artifacts
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: ModifiedFiles
+          path: .
